# How to use this manual {#howto}

This manual has been developed specifically for Biology students. We are increasing the focus on quantitative skills in our Biology curriculum, in response to changing demands and emphasis within the field of biology itself. In first year Biology (BIOL 1001/1002) we are introudcing students to R sofware and basic statistical concepts. This manual acts as the tutorial guide to help students learn the basics of R that will form the foundation for more advanced quantitative work in upper year Biology courses. We anticipate that this guide will also be a useful resource manual that you will refer back to as you use R in applications specific to your future courses. This manual will be updated annaully, so we recommend you bookmark the html page instead of printing out the manual. 

While working through the manual, we recommend that you set up your computer screen so that you can see your browser and the R Studio software at the same time. You can experiment with re-sizing windows and if you have two monitors, that will be really handy. Or, if you have access to a laptop and a tablet, we recommend using RStuio on your laptop and opening the manual in the browser on your tablet so that you can move between the two easily. 

For first year students, we recommend that you start by reading Chapter \@ref(intro),  this Chapter and Chapter \@ref(code-intro) to give yourself some background. You may also find it helpful to check the Glossary to familiarize yourself with some computer terminology. For there, you can  prodceed to follow the steps in Chapter \@ref(install) to install R and R studio. If you are having issues with installing the software, check the FAQ (Frequently Asked Questions) section in Appendix A. Once you have the software installed, you can read through Chapter \@ref(rstudio) (with the software open in a different window/screen!) and start to learn to navigate through the software.

After you've familiarized yourself with the layout of the software, you can start to work with it! Don't worry - you can't break it! With the manual and R studio open, work through Chapter \@ref(rintro). Whenever you see text in the manual in a grey box and in the Courier font, this is an example of code that we want you to try. Note that you should type the code EXACTLY as it is written. As you progress through the manual, we will sometimes give you only part of the code, or we will give code that has a deliberate mistake in it. This is not to frustrate you - rather it is a way for you to start to develop your problem solving skills. Read the text before and after the example code carefully for clues as to what you should do.

From there, proceed through the chapters as assigned by your lab instructor for each week of the quant labs. 

Excpet to get stuck. This is normal when learning a new skill. Everyone who uses R, including professors who have used it for years, gets error messages and has bugs in their code. If you look for help using the resources provided in Chapter \@ref(help) or ask for help as specified in Chapter \@ref(howtoask), you should be able to get "unstuck".

In terms of the assignments - for BIOL 1001/1002, you should complete all the parts of the manual where it says **HAND IN**. How much of the manual to complete in each week will be provided by your lab instructor. You can do the **HAND IN** exercises in RStuio and then cut and paste your answers into a Word document or GoogleDoc file for handing in. 

Once you've finished the first year labs, don't forget that you have this resource! Bookmark the page so that when you find yourself using R again in future courses (and you will!) you can quickly re-familiarize yourself with it. Working with R is like learning a new langugage or playing a musical instrument. If you don't do it for awhile, your skills get rusty. However, if you have documented what you've done, and reveiw the manual, you can quickly catch up to where your skills were and then move on and master new skills. Before you know it, you will be confidently doing quantitative work in R, which will increase your knowledge,enhance your ability to do advanced biology work, and give you a marketable skill in the work world. 
