# Introduction to programming {#code-intro}

## What is a computer? 

Computers are tools that can do mainly four things: take input (information), store the input as data, process the data, and output the results. The input is how you tell a computer what to do (e.g. with the mouse, keyboard, touchscreen, microphone). These inputs provide information that the computer stores in its memory. The computer's processor can access this information, manipulate it using algorithms or programs, and save the processed data back in the memory. The processing can consist of multiple operations, at the end of which the information can be outputted. The output depends on the computer and could be a matrix, a database, text, images, videos, games, etc.

## What is a program? 

A program is a sequence of instructions that tell a computer how to process the information provided as input. In simple words, programs are the recipes that tell the computer how to do or execute a task. Programs are also referred to as Apps, and when we execute a program or an App, we usually use the word "run" We can classify programs depending on where it runs. For example, web apps run on web browsers (e.g. Google Docs), mobile apps run on your smartphone (e.g. Pokémon GO), and desktop apps are installed and run on your computer (e.g. Microsoft Word desktop app).

Computer programs are also called code. So, coding or programming is the action of writing instructions for computers to do specific tasks.

## What is a programming language?

The language of computers is called binary code. Binary code is a two-symbol system, often "0" and "1" (from the binary number system), which represent the states "off" and "on". In binary code, each character or instruction is assigned a pattern of binary digits (aka. bits). 

Unfortunately, it is hard for humans to understand binary code. Hence, to communicate with computers we need to use a special kind of language. A programming language is a language that can be translated into the machine binary code, but it is easier for humans to comprehend and write. Programming languages are developed to build programs.

There are hundreds of programming languages. In this guide, you will learn to code in the R language. R is an interpreted language, which means that the computer will read an instruction in the programming language, translate it into machine code, and then execute the machine code version. Once that instruction finished, the computer moves along to the next one, and performs the same task again until there are no more instructions to complete. Nevertheless, this is a fast process, and you do not need to worry about the steps that the computer is doing underneath the hood.

## Why code?

We are used to pointing our mouse and clicking on an icon to perform tasks on our computers. This visual process is intuitive to learn. However, when we have to repeat the same operation thousands of times, clicking and dragging become tedious and inefficient in delivering instructions to the computer. For example, you have to plot the results of an experiment conducted 30 times. But, the machine that does the measurements stores the data in individual folders. So, first, you have to find each datafile. Then, you have to copy the last line of each datafile into a single file. You can complete all these tasks using the mouse, although you would be clicking at your desk for several hours. Imagine that there was an error in the data, or that you have to repeat the experiment. Now you have to continue clicking some more hours and can potentially commit a mistake while completing this repetitive task. In a situation like this (and many others!), being able to write a program that performs the operations for you is the best skill. Coding allows you to do repetitive tasks automatically and fast, as many times as you want. Further, programming enables you to do many complicated processes (e.g. data analyses and model simulations) and increase the reproducibility and repeatability of your research. 

Learning to code takes effort and time. As with any language, you will have to learn new vocabulary. But, a small number of words or commands will get you a long way. Let's get started!
