# Hypothesis, predictions and equations {#hypothesis}

(**Sorry Joany, I meant this one: https://github.com/ahurford/quantitative-training-2/blob/master/first%20year/Biology%201001%20-%20Lab%20Manual%20-%20Fall%202019%20v0.4.docx in .docx with tracked changes: however, not all the track changes are accepted. You'll have to make a personal copy, accept the changes, cut and paste then just do a bit with the formatting, symbols and boxes**)

https://github.com/ahurford/quantitative-training-2/blob/master/first%20year/Biology%201001%20-%20Lab%20Manual%20-%20Fall%202019%20v0.4.docx

The process of science is often called the scientific method.
Many scientific investigations begin with the statement of a problem, 
which is usually worded in the form of a question. Problems should be clearly expressed 
and worded such that they have a specific answer. 
The proposed answer to the problem is termed an hypothesis. 
Hypotheses are formulated generally on the basis of some preliminary observations 
in combination with prior knowledge.
	
Consider the problem:  how does the presence of a concentration gradient affect the direction of osmosis?  There are three possible answers to this problem:

1.	Water diffuses from a hypertonic solution into a hypotonic solution.
	
2.	Water diffuses from a hypotonic solution into a hypertonic solution.
	
3.	Water diffuses equally in both directions.
	
All three meet the basic requirement of an hypothesis, namely, they are predictive, are clearly expressed and are an answer to the problem; however, #2 is the most likely hypothesis.
	
Experiments, observational studies, and mathematical models are designed 
and carried out to test the validity of hypotheses. 
Experiments represent a practical set of circumstances that determine whether predictions generated from the hypothesis will come to pass if the hypothesis holds true. Consider an osmometer containing a 30% glucose and dye solution placed in a beaker containing distilled water. If hypothesis #2 holds true water will diffuse from the hypotonic solution (the water in the beaker) into the hypertonic solution (the 30% glucose and dye solution in the osmometer) and the water will rise in the pipette. Note how this prediction was generated using the if ... then ... format.

i.e.	if the hypothesis holds true
		then a specific event will occur (prediction)
	
e.g.	If water diffuses from a hypotonic solution into a hypertonic solution (hypothesis)
		then water will diffuse from the beaker into the osmometer causing the water in the pipette to rise.
	
Although hypotheses and predictions are similar, two basic differences exist: hypotheses are general, predictions are specific; hypotheses are written in the present tense, predictions in the future tense.
	
Hypotheses are tested using statistics, and this involves writing the hypothesis as an equation. 
Generally, a hypothesis describes the affect of one factor on another, for example, the effect of a concentration gradient on the direction of osmosis. These factors are called variables and are of two types: the variable that is changed (varied) by the experimenter is called the INDEPENDENT VARIABLE, and the variable that changes as a consequence of the changes to the independent variable is called the DEPENDENT VARIABLE. In this example the concentration gradient is the independent variable because it is created by the experimenter and the direction of osmosis is the dependent variable because it is affected directly by the concentrations inside and outside the osmometer.
	
(**MORE HERE**)

In carrying out an experiment, observations are made and recorded. These observations are collectively the results of the experiment.  Good experimental design demands that only one independent variable is tested at a time (i.e. all other variables/conditions are kept constant so that any changes in the dependent variable can be regarded as due to the particular independent variable being tested). 
	
Experiments typically have two basic components: a CONTROL GROUP and an EXPERIMENTAL GROUP which differ with respect to only one factor, the independent variable. In the experimental group the independent variable is varied; whereas, in the control group it is not varied. In this way the control demonstrates (if there is no change to the dependent variable) that no other factor is affecting the dependent variable except the independent variable, and serves as a standard of comparison with the experimental group. Since we hypothesized that water diffuses from a hypotonic solution into a hypertonic solution, the setup having the concentration gradient (i.e. hypotonic and hypertonic solutions separated by a membrane) is the experimental setup. A control for this would be another setup not having a concentration gradient (i.e., with equal concentrations on either side of a membrane). The only difference between the two groups is the presence of a concentration gradient, i.e. the factor being tested.
	
After the experiment has been completed the results are analyzed, by applying statistics and, if necessary, plotted on graphs to show any general trends in the way the independent variable affects the dependent variable. Following statistical and graphic analysis the results are discussed. The discussion tries to account for why the independent variable affects the dependent variable (or why not?). One might also discuss the appropriateness of the experimental design in testing the hypothesis or any sources of error (factors also affecting the dependent variable) that may have been present in the experiment. Often times in articles published in scientific journals, authors tend to relate how this experiment relates to previous published work in this field or how the new knowledge gained from their study can be applied to other situations.

As a consequence of the discussion of the results, a conclusion may be formulated as to the extent to which the original hypothesis is, or is not, supported. An hypothesis which has been repeatedly supported by the results of experiments so that a high degree of confidence is placed in its validity is called a theory. When the confidence in its validity is even higher the hypothesis has the status of a law.

(**Up to here is the content of "Appendix II - The Scientific Method".**
**Should we continue with "Appendix III - Writing up Experiments"?**)
